const PATH = Object.freeze({
  AGREEMENT: '/agreement',
  CLASSES: '/classes',
  COURSES: '/courses',
  CREATE_MEETING: '/admin/meetings',
  DASHBOARD: '/dashboard',
  DEMO: '/demo',
  ERROR: '/error',
  EVALUATION: '/evaluations',
  EXAMS: '/exams',
  EXCHANGE: '/exchange',
  EXERCISES: '/exercises',
  FEEDBACK: '/feedback',
  FORGOT: '/forgot',
  GIFT: '/gift',
  LOGIN: '/login',
  LOGOUT: '/logout',
  MEETINGS: '/meetings',
  MODELS: '/models',
  PASSWORD: '/dashboard/settings/password',
  PAYMENTS: '/plans',
  QUALITY: '/quality',
  REQUIRED: '/required',
  RESET: '/reset',
  RESULTS: '/results',
  SECTIONS: '/sections',
  SETTINGS: '/dashboard/settings',
  SIGN_UP: '/signup',
  STREAMING: '/streaming',
  TESTING: '/testing',
  VERIFICATION: '/verification',
  LATEST: '/evaluations/latest',
  NOTIFICATIONS: '/notifications',
  STATS: '/stats',
  UNIT_1: '/unit-1',
  CONNECTED_UNIT: '/courses/:courseSlug/units/:unitSlug',
  GRAMMAR: '/grammar',
  VOCABULARY: '/vocabulary',
  LISTENING: '/listening',
  READING:   '/reading',
  READING_B: '/reading-b',
  READING_C: '/reading-c',
  SPEAKING:   '/speaking',
  SPEAKING_C: '/speaking-c',
  WRITING:   '/writing'
})

export default PATH
